### ISSUE TITLE
Errno 10061

### ISSUE THREAD

**Issue by mrvenomous15** [mitre/cascade-server#6]
While attempting to setup, I am getting Errno 10061. Below is the entire message.

```
Initializing database...
Importing collection attack_technique
Traceback (most recent call last):
  File "cascade.py", line 179, in <module>
    app.settings.setup(auto_defaults=True)
  File "C:\windows\system32\cascade-server\app\settings.py", line 86, in setup
    import_database_from_file('misc/{}'.format(filename))
  File "C:\windows\system32\cascade-server\app\utils.py", line 122, in import_database_from_file
    import_database(dump, collections=collections, overwrite=overwrite)
  File "C:\windows\system32\cascade-server\app\utils.py", line 101, in import_database
    database[collection].insert_many(content)
  File "C:\Python27\lib\site-packages\pymongo\collection.py", line 753, in insert_many
    blk.execute(write_concern, session=session)
  File "C:\Python27\lib\site-packages\pymongo\bulk.py", line 521, in execute
    return self.execute_command(generator, write_concern, session)
  File "C:\Python27\lib\site-packages\pymongo\bulk.py", line 344, in execute_command
    with client._tmp_session(session) as s:
  File "C:\Python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Python27\lib\site-packages\pymongo\mongo_client.py", line 1576, in _tmp_session
    s = self._ensure_session(session)
  File "C:\Python27\lib\site-packages\pymongo\mongo_client.py", line 1563, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Python27\lib\site-packages\pymongo\mongo_client.py", line 1516, in __start_session
    server_session = self._get_server_session()
  File "C:\Python27\lib\site-packages\pymongo\mongo_client.py", line 1549, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Python27\lib\site-packages\pymongo\topology.py", line 427, in get_server_session
    None)
  File "C:\Python27\lib\site-packages\pymongo\topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 10061] No connection could be made because the target machine actively refused it
```

**Comment by unkempthenry** [comment]
It sounds like there's not a local mongodb service running.  Cascade is trying to connect to it on via 127.0.0.1:27017 and can't find it.  The installation process for mongo varies by OS, but it's well document here: https://docs.mongodb.com/manual/administration/install-community/
